#!/bin/bash
# Location: Anywhere

# Add existing 'ubuntu' user to 'www-data' group
sudo usermod -a -G www-data ubuntu;

# Set the ownership of the files/directories
sudo chown -R www-data:www-data /var/www/html/;

# Set group ownership inheritance
sudo chmod g+s /var/www/html/;

# Set the permissions of the files/directories
sudo find /var/www/html/ -type d -exec chmod 755 {} \;
sudo find /var/www/html/ -type f -exec chmod 644 {} \;

# Give `write` permissions to the group (for editing files via FTP)
sudo chmod -R g+w /var/www/html/;
